name: Ping API Monitor

on:
  schedule:
    - cron: "*/5 * * * *" # tiap 5 menit
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call TwaryAPI Monitor
        run: curl -s https://testwary.vercel.app/api/monitor